### PR TITLE
subjectLimit option usage and validation

### PR DESCRIPTION
**Pull request by storageddd**
Current changes solve next problems:

1. subjectLimit property overrides by defaultMaxLineWidth.
2. Subject message validates by subjectLimit property, but when it trims, include prefix and scope – trim does not correct.

### CODE REVIEW

**Comment by storageddd** [comment]
@leonardoanalista, can you review changes?

**Comment by leonardoanalista** [comment]
thanks for the PR! 👏 👏 👏

**Comment by storageddd** [comment]
@leonardoanalista, can you update version of the package? It can't be used in other projects. Because last version tagged as 6.2.0 and it version doesn't includes this updates. Thanks!

**Pull request merged**
