### PR TITLE
Use airbnb eslint and prettier

### PR DESCRIPTION
**Pull request by leonardoanalista**
Here is a massive refactoring on code style. Hopefully this codebase will look a lot better and more devs can contribute:

* use "airbnb-base" with no modifications for now
* there are still a few eslint lines disabled to be fixed soon
* add prettier

### CODE REVIEW

**Comment by leonardoanalista** [comment]
@RomanMinkin

**Comment by RomanMinkin** [comment]
Hi @leonardoanalista, i see you tagged me, is there anything I can help with?

**Comment by leonardoanalista** [comment]
I tried to add your user to the “request code review” button but couldn’t find your user. Somehow it worked in the comments. I was going to ask for a code review if you have time. I didn’t add new features here but there is a lot of code changed.

**Pull request merged**
