### PR TITLE
feat: add options to skip any question

### PR DESCRIPTION
**Pull request by yetithefoot**
Added config options that allow to skip any question. All false by default.

```javascript
  skipType: true,
  skipsScope: true,
  skipSubject: true,
  skipBody: true,
  skipBreaking: true,
  skipFooter: true  
```

### CODE REVIEW

**Comment by Creabine** [comment]
thx to @yetithefoot ,we need this feature too. @leonardoanalista  please merge this PR if it's possible, thx again!

**Comment by leonardoanalista** [comment]
it looks good to me. PR needs rebasing. We then merge 👍

**Comment by yetithefoot** [comment]
Sorry guys, did merge instead of rebase.

**Comment by yetithefoot** [comment]
@leonardoanalista not sure how to fix Travis warning. Can you assist here please?

**Comment by Creabine** [comment]
> rebase

it's fine ,I made a [pr](https://github.com/leonardoanalista/cz-customizable/pull/65) myself, hope it's ok.

**Comment by Creabine** [comment]
> @leonardoanalista not sure how to fix Travis warning. Can you assist here please?

It's fine, I made a new pr, I hope it's ok.

**Comment by leonardoanalista** [comment]
Option `skipQuestions{Array}` has been introduced and it provides this feature.

**Pull request closed without merging**
