### PR TITLE
feat(config): use find-config package to locate config

### LINKED ISSUE #10: postinstall in dev env
`postinstall` script in dev environment tries to create config file on 2 levels up. Seems it supposed to be a project root. But in dev environment (`git clone git@github.com:leonardoanalista/cz-customizable.git` + `npm i`) it is not true since current folder is top level project. In my case it tries to write file at `/home/.cz-config.js` and fails.

### PR DESCRIPTION
**Pull request by Guria**
There is no need in creating symlink with postinstall script so it was removed.
Getting started instruction provides command to get config template.

closes #10
includes #19

### CODE REVIEW

**Comment by leonardoanalista** [comment]
For PR #20  `use find-config package to locate config`, Is this a breaking 
I can't see the commit with `breaking change` footer?

**Comment by Guria** [comment]
@leonardoanalista see latest comment in #10

**Comment by leonardoanalista** [comment]
because this should bump the major version to 3 right?

**Comment by Guria** [comment]
@leonardoanalista it doesn't breaks anything in fact

**Comment by leonardoanalista** [comment]
great stuff! cheers

**Comment by Guria** [comment]
I just made it to fit my need :)

**Comment by leonardoanalista** [comment]
The symlink and auto-file creation was a bit arguable. Jshint, eslint and others you have to create config file manually. Also now this module is more inclusive to Windows clients.

**Pull request merged**
